### ISSUE TITLE
issueベースの開発

### ISSUE THREAD

**Issue by y-yany** [y-yany/PathFinder#38]
■Webアプリの概要
散歩コースを共有・検索できるサービスです。
- 散歩コースを作成・投稿することができます。
- コースの見どころやスポット (カフェや休憩場所など) を追加できます。
- 現在の位置情報から、周辺のコースを検索することができます。
- テーマ (例：海岸沿い) に合わせたコースを検索することができます。

■1週間辺りの開発に向けられる時間
- 1週間あたり：18時間

■ProjectsのURL
https://github.com/users/y-yany/projects/2/views/1

■MVPリリースまで
- [ ] rails new
- [ ] Herokuにデプロイ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] コース作成・投稿機能
- [ ] コース一覧
- [ ] コース詳細
- [ ] コース削除機能

■MVP後
- [ ] コース編集機能
- [ ] コース検索機能
- [ ] コメント投稿機能
- [ ] スポット作成機能
- [ ] タグ機能
- [ ] ブックマーク機能
- [ ] いいね機能
- [ ] プロフィール機能
- [ ] Xシェア機能
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] Google認証によるログイン・ユーザー登録機能
- [ ] 検索機能のオートコンプリート
- [ ] パスワードリセット機能
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] CI（GitHubActions）
- [ ] ファビコン
- [ ] 独自ドメイン
- [ ] レスポンシブ対応
- [ ] PWA対応

■MVPレビュー依頼予定日
予定日：2025年 1月 15日

**Comment by tarakish** [comment]
Issueの内容までよく記載されていますね！LGTMです！
MVPリリースに向けて開発頑張ってください。

**Comment by y-yany** [comment]
ご確認いただきありがとうございます！
引き続きよろしくお願いします！
